# Generated by Django 4.1.7 on 2023-02-19 03:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Postnew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postname", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", ckeditor.fields.RichTextField()),
                ("images", models.ImageField(upload_to="photos/products")),
                ("is_available", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
